Added content for redis installation and configuration
developer-portal/content pull request #341
Opened 2020-05-14 21:31 UTC by BharatKalluri

2020-10-12 17:26 UTC, pvalena commented
Hello,
thanks for the PR!

Could you add logo as well?
https://github.com/developer-portal/website/tree/master/static/logo

2021-04-01 17:01 UTC, BharatKalluri commented
Hi @pvalena ,
The other PR to add logo was merged a while back. Can we merge this PR since that is merged ?

2021-06-02 10:04 UTC, pvalena commented
Sorry, this has somehow fallen through my poor 'ticket management'. We will address this in next release (end of June).

2021-06-11 14:25 UTC, jackorp requested changes
Please look at the contribution guide: https://developer-portal.github.io/contributing/write-introduction.html

Also have only one title per page (here it is `# Redis`), the rest should be only subsections, i.e. second-level header `## My header`

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +# Quick start
Please use the Second level header  (`## Quick start`), the title should be only one.
```suggestion
## Quick start
```

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +and after redis server restart, all clients must execute `AUTH <AuthPassword>` to execute commands in redis.
```suggestion
and after the Redis server restarts, all clients must execute `AUTH <AuthPassword>` to be able to execute commands in Redis.
```

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +sudo nano /etc/redis.conf
Fix the configuration file path to be `/etc/redis/redis.conf`.

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +Secure redis by enabling authentication. Add this line in redis.conf
It would be better if the `redis.conf` was a full path, i.e. `/etc/redis/redis.conf`

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +Redis should be always restarted after changing settings. Restart redis by running
From Contributing guidelines: [Be sure](https://developer-portal.github.io/contributing/write-general-writing-hints.html#be-sure)

```suggestion
Redis must always be restarted after changing settings. Restart Redis by running:
```

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +Redis installation on fedora
Let's be a bit more verbose:
```suggestion
To install Redis on Fedora, run the following commands:
```

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +To test, run
I am not sure what this is testing, my installation, am I testing the CLI client?

2021-06-11 14:25 UTC, jackorp commented on tech/database/redis/about.md
> +$ redis-cli ping # output will be pong
Consider adding the expected output under this command and with a description along the lines of `Result of running the test looks like this`.

2021-07-19 12:12 UTC, BharatKalluri commented
I've deleted my fork by mistake. I've created another PR incorporating all the suggested changes by @jackorp over at https://github.com/developer-portal/content/pull/390 
Let me know if there is anything else which needs to change, I'll be closing this PR since #390 is open. Thanks for the detailed review :)

2021-07-19 12:12 UTC, closed without merging