Refactor cassandra page
developer-portal/content pull request #342
Opened 2020-05-22 11:27 UTC by tpardeshi

Refactor Cassandra page into multiple files.

2020-06-02 10:24 UTC, pvalena commented
Wow I really appreciate the work put into it, thanks!

Let me go through this next week. (But others can help with review as well :))

2020-06-04 06:49 UTC, tpardeshi commented
Sure :)

2020-10-12 17:19 UTC, pvalena commented
Sorry for this to take so long, we're blocked on https://github.com/developer-portal/website/pull/104.

2021-03-12 11:12 UTC, pvalena requested changes
Please check the comments. Mostly you've forgotten about the jekyll headers, so it wouldn't be rendered properly.

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_configuration.md
> +## How to configure Cassandra
You're missing a header here.

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_cluster.md
> +## Running a Cassandra cluster
You're missing a jekyll header here.

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_configuration.md
> +## How to configure Cassandra
Also the page should start with 
```
# Title
```
(not a `## Subtitle`)
Please check our [contribution guide](https://developer-portal.github.io/doc/file-structure.html).

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_documentation.md
> +## Documentation
Should be probably in a "about.md" page.

Also it's missing a header (I think for most of the pages, along with the `##` instead of `#`).

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_installation.md
> +## Quick start
All of content here in developer portal should be a "Quick start" or a reference to some documentation. Not a documentation itself.

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_installation.md
> +$ sudo systemctl start cassandra                # initialize Cassandra server
Aren't you duplicating the `installation` page?

Please also check our [writing guide](https://developer-portal.github.io/contributing/write-introduction.html).

I'd avoid the `# comments ` at the end of the line, as not everyone know that they're the comments. Can you move it to a separate line?

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_language_connectors.md
> +
Please add some entry on how to install them / what they are instead of link to package sources.

2021-03-12 11:12 UTC, pvalena commented on tech/database/cassandra/cassandra_production_environment.md
> +Follow the instructions to "Enabling remote access to server" from cassandra_configuration.md
You can actually write this as a link. It's not a `.md`, but `.html` - otherwise standard markdown link ([absolute](https://github.com/developer-portal/content/edit/master/tools/docker/about.md)).

2021-06-11 15:17 UTC, jackorp commented
Ping... @tpardeshi  Are you still interested in advancing this PR?

2024-11-26 11:15 UTC, jackorp commented
Closing stalled PR.

2024-11-26 11:15 UTC, closed without merging