Update mobile-installation.md
developer-portal/content pull request #344
Opened 2020-06-20 23:36 UTC by david-kariuki

I have proposed some correction to the content page of the developer-portal mobile-installation section. I have proposed the edits to make the instructions simpler for everyone and especially newbies.

2020-10-12 17:48 UTC, pvalena requested changes
Thanks for the rewording, but please drop the changes adding `.` for headers.

2020-10-12 17:48 UTC, pvalena commented on start/sw/mobile-app/mobile-installation.md
> +# Mobile application.
We're not using dots for headers.

2021-06-11 15:17 UTC, jackorp commented
Ping... @david-kariuki Are you still interested in advancing this PR?

2022-04-29 23:46 UTC, naizar86 approved these changes
> # @`
Duplicate of #`

2022-04-30 11:11 UTC, jackorp commented
If anyone is interested in advancing this PR, feel free to resubmit.

2022-04-30 11:11 UTC, closed without merging

2022-05-18 16:55 UTC, david-kariuki commented
No