feat: remove devAssistant
developer-portal/content pull request #378
Opened 2021-04-20 15:09 UTC by gombosg

devAssistant is dead :(

2021-04-20 22:07 UTC, pvalena commented
Thanks!
Could you also remove the entries and references to it from `tech/languages/java/java-build-tools-installation.md`?

2021-04-23 08:35 UTC, gombosg commented
I reworked and expanded them instead if you're OK with that.

2021-04-23 16:37 UTC, pvalena requested changes
Looks good! My only question would be how to get the `mvn` executable.

Pointing simply to another quick start guide is also fine with me (instead of duplicating the content here).

Is there anything benefitial here that 's not in the referenced guide?

2021-04-23 16:37 UTC, pvalena commented on tech/languages/java/java-build-tools-installation.md
> +Use the command from the [Maven quick start guide](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html):
This sounds great! But don't we have the `mvn` packaged in Fedora?

If it's about the guide, please put the reference after the `quick start` "text" instead.

2021-04-23 16:37 UTC, pvalena commented on tech/languages/java/java-build-tools-installation.md
> +$ git init
I plan to do a standalone `git` quickstart, so I'll move most of this later on, leaving just a reference.

2021-05-31 16:53 UTC, pvalena commented on tech/languages/java/java-build-tools-installation.md
> +Use the command from the [Maven quick start guide](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html):
Let's address this in standalone PR if it needs to be changed (**is mvn in Fedora?**).

2021-05-31 16:54 UTC, merged