vagrant-libvirt.md: QEMU / Session changes
developer-portal/content pull request #419
Opened 2022-02-21 13:58 UTC by pvalena

In Fedora, QEMU / Session is used. This is not documented properly. Advice users on what it is and how to revert in case it doesn't work for them.

2022-02-21 17:32 UTC, jackorp requested changes
This change is LGTM. However, I'd like to have a more detailed "howto" for Fedora users to use this feature.

2022-02-21 17:32 UTC, jackorp commented on tools/vagrant/vagrant-libvirt.md
> +- Upstream documentation: https://github.com/vagrant-libvirt/vagrant-libvirt#qemu-session-support
These links are not clickable. Please use the `[name](link)` markdown format so that the links become clickable.

2022-02-24 13:58 UTC, pvalena commented
> This change is LGTM. However, I'd like to have a more detailed "howto" for Fedora users to use this feature.

Please elaborate. What do you want me to do? What detail is missing? It's not supposed to be step-by-step guide. If you don't know how to use Vagrantfile, you need upstream docs (or do you know a better place?). If you do, you just add the directive.

2022-02-24 13:59 UTC, pvalena commented
FTR: It's not a feature, it's a workaround for an issue we have only in Fedora, as noone else switched to **QEMU Session** yet for Vagrant (the better approach).

2022-02-24 14:51 UTC, jackorp commented
> > This change is LGTM. However, I'd like to have a more detailed "howto" for Fedora users to use this feature.
> 
> Please elaborate. What do you want me to do? What detail is missing? It's not supposed to be step-by-step guide. If you don't know how to use Vagrantfile, you need upstream docs (or do you know a better place?). If you do, you just add the directive.

Hmm, I was probably tired and didn't read properly, sorry.

I'd say a "nice to have" would be to have the Vagrantfile option, that disables this feature, specified on this page? And if users would want to know more then they can refer to the change and docs.

2022-03-21 12:27 UTC, jackorp commented
Thanks!

Let's merge this.

2022-03-21 12:27 UTC, merged

2022-03-21 15:02 UTC, pvalena commented on tools/vagrant/vagrant-libvirt.md
> +- Fedora change: [https://fedoraproject.org/wiki/Changes/Vagrant_2.2_with_QEMU_Session](https://github.com/developer-portal/content/pull/423)
@jackorp  This is wrong.