Added info about mod_wsgi & dependencies
developer-portal/content pull request #481
Opened 2023-06-18 06:40 UTC by SomeAB

I added further information about how to install mod_wsgi first using pip venv method, and related dependencies as of Python 3.11, pip 23.1, mod_wsgi 4.9.4

Original pypi page briefly mentions python3-devel as a dependency, but missing a mention of the package name, when talking about Fedora related dependencies. 

This just adds more clarity, if someone wants to install mod_wsgi before installing django.

2023-08-11 09:19 UTC, jackorp requested changes
Mostly good, though I'd prefer if the dependencies were known for sure.

Thanks.

2023-08-11 09:19 UTC, jackorp commented on tech/languages/python/django-installation.md
> +Without installalling 'wheel' first, you will get a warning about legacy install method. See https://github.com/pypa/pip/issues/8559 for more details. Though as of pip 23.1, pythong 3.11, it should s
Typo
```suggestion
Without installalling 'wheel' first, you will get a warning about legacy install method. See https://github.com/pypa/pip/issues/8559 for more details. Though as of pip 23.1, python 3.11, it should still install correctly without wheel. Additional dependencies 'may' include python3-devel, httpd, httpd-devel, setuptools, redhat-rpm-config. 
```

2023-08-11 09:19 UTC, jackorp commented on tech/languages/python/django-installation.md
> +Without installalling 'wheel' first, you will get a warning about legacy install method. See https://github.com/pypa/pip/issues/8559 for more details. Though as of pip 23.1, pythong 3.11, it should s
I don't really like the "may". Does it or does it not? If it does, it should be explicitly mentioned with a `dnf install` command, if it does not, it doesn't need to be mentioned.

2023-08-11 10:56 UTC, SomeAB commented
@jackorp okay, I will again check both 'source' build method & pip install method for dependencies. I agree. It should be clearer. Will post back in 2-3 days.

2024-09-10 08:39 UTC, SomeAB commented
I just checked this properly (sorry for late reply)

On the https://developer.fedoraproject.org/tech/languages/python/django-installation.html itself .. the above stated information might not be suitable

Modwsgi is a replacement for the outdated CGI (CGI is included in Apache by default). It can help run other frameworks as well like Flask. Modwsgi is also the recommended WSGI interface for Django (according to official Django Documentation)

I think it would be better to make a page, linked on the left side menu to add information about Modwsgi (i.e., it deserves a page of its own). 

However, there seems to be no way to raise a pull request for making a separate page (& might need manual intervention of the wiki moderator/admin)

If you feel like it, you can close this pull request

2024-09-13 17:25 UTC, jackorp commented
> However, there seems to be no way to raise a pull request for making a separate page (& might need manual intervention of the wiki moderator/admin). See below image:

Hmm... the closest I can find is https://developer-portal.github.io/doc/file-structure.html and https://developer-portal.github.io/doc/structure.html
you can basically copy-paste a page in the correct directory (there will probably be the other pages as well), edit the YAML on the top and write the correct contents.
Of course I can check & correct any wrong values, etc...

But I am not sure we have complete documentation for that process.

> If you feel like it, you can close this pull request

If you judge the content of this PR unsuitable, as described, in the current state, I will. I would of course welcome the contribution on a separate page. If you would like help with continuing on that separate page, please create an issue for this repo where we can collaborate on this.

Thanks.

2024-09-13 17:25 UTC, closed without merging